# The first stage: building the vue front-end

FROM node:18 as web-builder
WORKDIR /app
COPY main/manager-web/package*.json ./
RUN npm install
COPY main/manager-web .
RUN npm run build

# Phase 2: Building the java backend

FROM maven:3.9.4-eclipse-temurin-21 as api-builder
WORKDIR /app
COPY main/manager-api/pom.xml .
COPY main/manager-api/src ./src
RUN mvn clean package -Dmaven.test.skip=true

# Phase 3: Build the final image

FROM bellsoft/liberica-runtime-container:jre-21-glibc

# Install nginx and font library

RUN apk update && \
    apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/ \
    nginx \
    bash \
    fontconfig \
    ttf-dejavu \
    msttcorefonts-installer \
    && ACCEPT_EULA=Y apk add --no-cache msttcorefonts-installer \
    && fc-cache -f -v \
    && rm -rf /var/cache/apk/*

# Update font cache

RUN (printf 'YES\n' | update-ms-fonts || true) && fc-cache -f -v

# Configure nginx

COPY docs/docker/nginx.conf /etc/nginx/nginx.conf

# Copy the front-end build product

COPY --from=web-builder /app/dist /usr/share/nginx/html

# Copy the java backend jar package

COPY --from=api-builder /app/target/xiaozhi-esp32-api.jar /app/xiaozhi-esp32-api.jar

# exposed port

EXPOSE 8002

# startup script

COPY docs/docker/start.sh /start.sh
RUN chmod +x /start.sh
CMD ["/start.sh"]